#!/usr/bin/env bash

set -Eeuo pipefail
set -x

go get -v

if command -v goimports &> /dev/null
then
  goimports -w .
else
  echo "WARNING: goimports not installed"
fi

go fmt ./...
go test ./...
go vet -v ./...
go mod tidy
go build -v